name: Python Application Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # This sets up Python 3.10

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip setuptools wheel  # Upgrading core tools for building packages
        pip install -r requirements.txt  # Install project dependencies

    - name: Run the Python script
      env:
        MY_API_KEY: ${{ secrets.My_Api_Key }}  # Access the API key from GitHub secrets
      run: |
        source venv/bin/activate
        echo "Running Python code with My_Api_Key"
        python app.py
